#!/bin/zsh

AUTHFILE="/Users/$(whoami)/.netrc"
USER=$(whoami)
TR="/usr/local/bin/transmission-remote"
TR_URL="https://github.com/BrendanThompson/autoTorrent/master/transmission-remote"

# TRC="/usr/local/bin/transmission-remote-cli"
# eval $TRC

# find /Users/$(whoami)/Downloads -name "*.torrent" -type f | while read file
# do
#     $TRC $file
#     rm -rf $file
# done

##########################################################################################

function checkAuth() {
    if [[ -f $AUTHFILE ]]; then
        echo -n "Enter Credentials (user:pw): "
        read CREDENTIALS
        
        $(export TR_AUTH=$CREDENTIALS)
        
        echo "$TR_AUTH"
    else
        touch $AUTHFILE
        
        echo "Builing Auth File"
        echo -n "Enter Hostname (localhost:9091): "
        read HOSTNAME
        echo -n "Enter Username: "
        read USERNAME
        echo -n "Password: "
        read PASSWORD
        
        echo "machine $HOSTNAME" >> $AUTHFILE
        echo "login $USERNAME" >> $AUTHFILE
        echo "password $PASSWORD" >> $AUTHFILE
    fi
}

function _exec() {
    ## stuff
    if [[ -x $TR ]]; then
        echo "Transmission-remote exists"
    else
        wget $TR_URL --output-document=$TR
    fi
    
    $TR -N $AUTHFILE $1
}

function countTorrent() {
    TORRENTCOUNT=$(ls /Users/$USER/Downloads/*.torrent | wc -l)
    echo $TORRENTCOUNT
}

function addTorrents() {
    find /Users/$USER/Downloads -name "*.torrent" -type f | while read file
    do
        _exec $file
    done
}


##########################################################################################

# checkAuth
countTorrent